from enum import Enum

class Relations(Enum):
    """Standardized relationship types"""
    HYPERNYM = "hypernym"
    HYPONYM = "hyponym"
    INSTANCE_HYPERNYM = "instance_hypernym"
    INSTANCE_HYPONYM = "instance_hyponym"
    MEMBER_MERONYM = "member_meronym"
    MEMBER_HOLONYM = "member_holonym"
    PART_MERONYM = "part_meronym"
    PART_HOLONYM = "part_holonym"
    SUBSTANCE_MERONYM = "substance_meronym"
    SUBSTANCE_HOLONYM = "substance_holonym"
    SIMILAR_TO = "similar_to"
    VERB_GROUP = "verb_group"
    DERIVATIONALLY_RELATED_FORM = "derivationally_related_form"
    MEMBER_OF_DOMAIN_USAGE = "member_of_domain_usage"
    HAS_DOMAIN_USAGE = "has_domain_usage"
    MEMBER_OF_DOMAIN_REGION = "member_of_domain_region"
    HAS_DOMAIN_REGION = "has_domain_region"
    MEMBER_OF_DOMAIN_TOPIC = "member_of_domain_topic"
    HAS_DOMAIN_TOPIC = "has_domain_topic"
    DEPENDS_ON = "depends_on"
    IMPLEMENTS = "implements"
    RESULTS_IN = "results_in"
    IS_A = "is_a"
    PART_OF = "part_of"
    ENABLES = "enables"
    RELATED_TO = "related_to"